server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:assetManagementDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  sql:
    init.mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: update

      Spring:
      application:
      name: Profile-Management
